# Use official Node.js 14 as a parent image
FROM node:14 as build-stage

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .

# Build the app
RUN npm run build

# Use official Python 3.7 as a parent image
FROM python:3.7-slim

# Set the working directory in the container to /backend
WORKDIR /backend

# Copy the backend directory contents into the container at /backend
COPY ./verinote/api .

# Install pipenv and backend dependencies
RUN pip install pipenv && pipenv install --system --deploy

# Start the Flask app
CMD flask run --host=0.0.0.0 --port=5000

# Copy frontend build artifacts from build-stage
COPY --from=build-stage /app/out ./out

# Expose port 3000 for the Next.js app
EXPOSE 3000

# Start the Next.js app
CMD [ "npm", "run", "dev" ]
