# Build the Next.js app
FROM node:14 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Set up the Python environment
FROM python:3.7-slim
WORKDIR /app
COPY --from=build-stage /app/out ./out
COPY ./verinote/api ./api
RUN pip install -r .verinote/api/requirements.txt

# Start the Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]
